// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameApk = "apk"

// Apk mapped from table <apk>
type Apk struct {
	ID                       int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Title                    string    `gorm:"column:title" json:"title"`
	Description              string    `gorm:"column:description" json:"description"`
	DescriptionHTML          string    `gorm:"column:descriptionHTML" json:"descriptionHTML"`
	Summary                  string    `gorm:"column:summary" json:"summary"`
	Installs                 string    `gorm:"column:installs" json:"installs"`
	MinInstalls              int32     `gorm:"column:minInstalls" json:"minInstalls"`
	RealInstalls             int32     `gorm:"column:realInstalls" json:"realInstalls"`
	Score                    float64   `gorm:"column:score" json:"score"`
	Ratings                  int32     `gorm:"column:ratings" json:"ratings"`
	Reviews                  int32     `gorm:"column:reviews" json:"reviews"`
	Histogram                string    `gorm:"column:histogram" json:"histogram"`
	Price                    int32     `gorm:"column:price" json:"price"`
	Free                     bool      `gorm:"column:free" json:"free"`
	Currency                 string    `gorm:"column:currency" json:"currency"`
	Sale                     bool      `gorm:"column:sale" json:"sale"`
	SaleTime                 string    `gorm:"column:saleTime" json:"saleTime"`
	OriginalPrice            int32     `gorm:"column:originalPrice" json:"originalPrice"`
	InAppProductPrice        string    `gorm:"column:inAppProductPrice" json:"inAppProductPrice"`
	Developer                string    `gorm:"column:developer" json:"developer"`
	DeveloperID              string    `gorm:"column:developerId" json:"developerId"`
	DeveloperEmail           string    `gorm:"column:developerEmail" json:"developerEmail"`
	DeveloperWebsite         string    `gorm:"column:developerWebsite" json:"developerWebsite"`
	DeveloperAddress         string    `gorm:"column:developerAddress" json:"developerAddress"`
	PrivacyPolicy            string    `gorm:"column:privacyPolicy" json:"privacyPolicy"`
	Genre                    string    `gorm:"column:genre" json:"genre"`
	GenreID                  string    `gorm:"column:genreId" json:"genreId"`
	Icon                     string    `gorm:"column:icon" json:"icon"`
	HeaderImage              string    `gorm:"column:headerImage" json:"headerImage"`
	Screenshots              string    `gorm:"column:screenshots" json:"screenshots"`
	Video                    string    `gorm:"column:video" json:"video"`
	VideoImage               string    `gorm:"column:videoImage" json:"videoImage"`
	ContentRating            string    `gorm:"column:contentRating" json:"contentRating"`
	ContentRatingDescription string    `gorm:"column:contentRatingDescription" json:"contentRatingDescription"`
	AdSupported              bool      `gorm:"column:adSupported" json:"adSupported"`
	ContainsAds              bool      `gorm:"column:containsAds" json:"containsAds"`
	Released                 string    `gorm:"column:released" json:"released"`
	Updated                  time.Time `gorm:"column:updated" json:"updated"`
	Version                  string    `gorm:"column:version" json:"version"`
	AppID                    string    `gorm:"column:appId" json:"appId"`
	URL                      string    `gorm:"column:url" json:"url"`
	Categories               string    `gorm:"column:categories" json:"categories"`
	IsHot               string    `gorm:"column:isHot" json:"isHot"`
}

// TableName Apk's table name
func (*Apk) TableName() string {
	return TableNameApk
}
