// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameCategory = "category"

// Category mapped from table <category>
type Category struct {
	ID      int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	StoreID string `gorm:"column:store_id" json:"store_id"`
	Name    string `gorm:"column:name" json:"name"`
	Status  int64  `gorm:"column:status" json:"status"`
	Icon    int64  `gorm:"column:icon" json:"icon"`
}

// TableName Category's table name
func (*Category) TableName() string {
	return TableNameCategory
}
